# Assignment-1

TRI ATMAJA

1. Create a 4x4 matrix with values ranging from 0 to 3.\
(The following image is just as an example. It doesn't represent the real image of arrays in the question)
![](image/assignment2.png)

In [42]:
import numpy as np
from numpy import random

In [70]:
# Jawaban tipe-1
a = np.random.randint(4, size=(4, 4))
a

array([[3, 1, 2, 1],
       [3, 2, 0, 0],
       [2, 3, 3, 3],
       [1, 0, 0, 3]])

In [63]:
#Jawaban tipe ke-2
b = np.zeros((4,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
b += np.arange(4)
b

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

2. Create and array with shape of 4x4 and turn it into two arrays along the second axis.\
![](image/assignment.png)

In [65]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
d = np.hsplit(c, 2)
d

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [95]:
e = np.arange(1,26).reshape(5,5)
e

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [96]:
e[:2] = 0

In [97]:
N_max = int(np.sqrt(len(e) - 1))
for j in range(2, N_max + 1):
    e[2*j::j] = False
    
e

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [ 0,  0,  0,  0,  0]])

In [101]:
import numpy as np
import math

def is_prime(n):
    if n % 2 == 0 and n > 2: 
        return False
        return all(n % i for i in range(3, int(math.sqrt(n)) + 1, 2))a = np.arange(1, 100)

foo = np.vectorize(is_prime)
pbools = foo(a)
primes = np.extract(pbools, a)
primes

SyntaxError: invalid syntax (<ipython-input-101-91a5c9954ede>, line 7)