# PERTEMUAN - 1

In [ ]:
# esc + a = insert cell above
# esc + b = insert cell below
# esc + double d = delete cell
# esc + m = markdown
# esc + y = code
# shift + enter = run
# esc + h = info semua shortcut

In [ ]:
# Numpy (numerical python): Numeric data
# Pandas: Analysis and Operation Data (pengolahan data)
# Matplotlib Visualisasi data

In [ ]:
# Note

# Type data: List; Tuple; Set; dictionary
# data 1 dimensi --> array --> shape: (n,) --> maksudnya 1 dimensi
# data 2 dimensi --> matrix --> array berdimensi 2 --> shape: (n,m) --> maksudnya baris n dan kolom m
# data 3 dimensi --> vector --> kumpulan dari beberapa MATRIX --> shape (n, m, l) --> maksudnya n set, m baris, l kolom

In [ ]:
# Note 2

# Speed/Performance
# functionalitas (function built-in sudah tersedia) - Performance
# space didalam numpy jauh lebih kecil

In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.1'

In [3]:
np.info(np.array)

array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (row major) unless 'F' is
    specified, in which case it will be in Fortran order (column major

In [ ]:
# shift + tab -> untuk docstring np.array()

## LIST vs NUMPY

### Performance

In [6]:
# Python list

list1 = [1, 2, 3, 4, 5]
list2 = [i*2 for i in range(1,6)]

print('list2:', list1)
print('list2:', list2)

list2: [1, 2, 3, 4, 5]
list2: [2, 4, 6, 8, 10]


In [7]:
print('tipe data dari list1:', type(list1))

tipe data dari list1: <class 'list'>


In [8]:
list1 + list2

[1, 2, 3, 4, 5, 2, 4, 6, 8, 10]

In [9]:
list3 = []
for a, b in zip(list1, list2):
    list3.append(a+b)
list3

[3, 6, 9, 12, 15]

In [10]:
list3 = []
for a, b in zip(list1, list2):
    list3.append(a*b)
list3

[2, 8, 18, 32, 50]

In [13]:
# numpy

np1 = np.array([1, 2, 3, 4, 5])
np2 = np.array([i*2 for i in range(1,6)])

print(np1)
print(np2)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [14]:
type(np1)

numpy.ndarray

In [15]:
np1 + np2

array([ 3,  6,  9, 12, 15])

In [16]:
np1 * np2

array([ 2,  8, 18, 32, 50])

In [17]:
np2 ** np2

array([         4,        256,      46656,   16777216, 1410065408],
      dtype=int32)

### Space

In [26]:
list1 = list(range(1, 1001))
', '.join([str(i) for i in list1])

'1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 22

In [27]:
len(list1) #menghitung total (banyaknya) data

1000

In [31]:
import sys
a = 1
type(a)

int

In [32]:
sys.getsizeof(a)

28

In [33]:
#jadi kalau banyak memori untuk data 1 - 1000
sys.getsizeof(a) * len(list1)

28000

In [34]:
# Array

np1 = np.arange(1, 1001)

In [22]:
len(np1)

1000

In [23]:
np1.size

1000

In [24]:
np1.itemsize

4

In [35]:
# jadi banyak data yang terpakai untuk 1000 jumlah data np1:

np1.size * np1.itemsize

4000

### Speed

In [36]:
size = 10_000_000

In [38]:
list1 = list(range(size))
list2 = list(range(size))
np1 = np.arange(size)
np2 = np.arange(size)

In [39]:
import time

In [41]:
# LIST

mulai = time.time()
result = [a+b for a, b in zip(list1, list2)]
print('python list membutuhkan waktu:', time.time() - mulai, 's')

python list membutuhkan waktu: 3.287320137023926 s


In [42]:
# Numpy

mulai = time.time()
result = np1 + np2
print('python numpy membutuhkan waktu:', time.time() - mulai, 's')

python numpy membutuhkan waktu: 0.34861159324645996 s


## Creating numpy arrays
There are some ways to initialize new numpy arrays:

- a Python list or tuples
- using functions that are dedicated to generating numpy arrays, such as arange, linspace, etc.
- reading data from files

## Penulisan Array dan perbedaannya dengan List

In [45]:
# vector: the argument to the array function is a list
v = np.array([1, 2, 3, 4, 5])
v

array([1, 2, 3, 4, 5])

In [46]:
type(v)

numpy.ndarray

In [54]:
v.shape

(5,)

In [50]:
# Matrix : the argument to the array function is a nested list
m = np.array([[1, 2, 3],
             [4, 5, 6]])

m

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
type(m)

numpy.ndarray

In [53]:
m.shape

(2, 3)

In [52]:
# List --> lihat perbedaannya

a = [1, 2, 3]
type(a)

list

#### x.shape

The difference between the v and m arrays is only their shapes. We can get information about the shape of an array by using the ndarray.shape property.

In [58]:
v.shape

(5,)

In [57]:
m.shape

(2, 3)

#### x.size

The number of elements in the array is available through the ndarray.size property

In [60]:
v.size

5

In [59]:
m.size

6

#### x.dtype
to check type of data

In [63]:
v.dtype

dtype('int32')

In [64]:
m.dtype

dtype('int32')

#### dtype=float/int/double/any
Common data types that can be used with dtype are: int, float, complex, bool, object, etc.
If we want, we can explicitly define the type of the array data when we create it, using the dtype keyword argument:

In [69]:
m = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)

m

array([[1., 2., 3.],
       [4., 5., 6.]])

## Create Matrix ZEROS

1 dimension
- np.zeros(x)

2-3 dimensions
should  be in tuple format
- np.zeros([x, y])
- np.zeros([x, y, z])

In [72]:
# One dimension

zeros_matrix = np.zeros(5)
zeros_matrix

array([0., 0., 0., 0., 0.])

In [78]:
# 2 dimension

zeros_matrix2 = np.zeros([5, 2])
zeros_matrix2

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [80]:
# 3 dimension

zeros_matrix3 = np.zeros([3, 2, 2])    
zeros_matrix3

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

### Matrix Ones
1 dimension
- np.ones(x)

2-3 dimensions
should  be in tuple format
- np.ones([x, y])
- np.ones([x, y, z])

In [88]:
# 1 dimension
matrix_ones_a = np.ones(3)
matrix_ones_a

array([1., 1., 1.])

In [87]:
matrix_ones_b = np.ones((3), dtype=int)
matrix_ones_b

array([1, 1, 1])

In [91]:
# 2 dimensions

matrix_ones2_a = np.ones([3, 5])  # harus dalam format tupple
matrix_ones2_a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [92]:
matrix_ones2_b = np.ones([3, 5], dtype=int)  # harus dalam format tupple
matrix_ones2_b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [93]:
#3 dimension

matrix_ones3 = np.ones((3, 4, 2)) #3 rows, 4 columns, 2 depth
matrix_ones3

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

## > Exercise 1

1. Create a matrix from a list which has 4 rows and 3 columns

In [100]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9],
             [10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [101]:
a.shape

(4, 3)

2. Create the following matrix
![](image/lat11.png)

In [96]:
b = np.array([[2, 7, 12, 0],
               [3, 9, 3, 4],
               [4, 0, 1, 3]])
b

array([[ 2,  7, 12,  0],
       [ 3,  9,  3,  4],
       [ 4,  0,  1,  3]])

3. Create a 2D matrix with size of 10

In [97]:
c = np.array([[1,2,3,4,5],
              [6,7,8,9,10]])
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [98]:
c.size

10

4. Create a 3D matrix of ones which has 2 rows, 3 columns, and 3 depth

In [104]:
d = np.ones([2, 3, 3])
d

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [105]:
d.shape

(2, 3, 3)

5. Make the following arrays from zeros arrays and with for loops
![](image/exercise1.png)

In [108]:
d = np.zeros((5, 3))
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [109]:
for line in d:
    print(line + 2)

[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]


---

### Using array-generating functions

For larger arrays it is inpractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in `numpy` that generate arrays of different forms. Some of the more common are:

#### arange

digunakan untuk menulis range angka dalam array

##### arguments: stop
np.arange(x)
x tanda akhir/stop dan exclussive

In [112]:
# create a range

x = np.arange(10)   #10 exclussive (tidak termasuk)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


##### arguments: start, stop
np.arange(x, y)

dimana x inclussive (termasuk) namun y exclussive (tidak termasuk)

In [116]:
x = np.arange(10, 20) # arguments: start, stop dimana 10 inclussive (termasuk) namun 20 exclussive (tidak termasuk)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

##### arguments: start, stop, step
np.arange(x, y, a)

In [117]:
x = np.arange(10, 20, 2) # arguments: start, stop, step
x

array([10, 12, 14, 16, 18])

In [118]:
x = np.arange(-1, 1, 0.1)
x

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

The number 9.00000000e-01 already is a floating point number.
It's written in scientific notation and is equivalent to 9 * 10**-1 or 0.9.

#### linspace

using linspace, both end points ARE included (inclussive)

`np.linspace(x, y, a)` --> dari x ke y dibagi 10 data dengan `interval yang sama`

In [119]:
np.linspace(0, 10, 10) #Unlike arange that uses step, linspace uses the number of sample

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [120]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

#### random data
uniform random numbers in [0,1]

x y berikut menunjukan dimensi dari array
- random.rand(x, y) --> random saja
- random.randn(x, y) --> random dengan distribusi normal

In [121]:
from numpy import random

In [123]:
random.rand(5,5)

array([[0.40497161, 0.81958789, 0.50087409, 0.5656256 , 0.9040589 ],
       [0.8031767 , 0.93300458, 0.78019153, 0.02507827, 0.6045066 ],
       [0.15171809, 0.5443494 , 0.69688801, 0.42014204, 0.71724243],
       [0.28642627, 0.83931512, 0.18918671, 0.57907592, 0.8888152 ],
       [0.63286075, 0.7851387 , 0.92748502, 0.68685859, 0.06161618]])

In [124]:
# standard normal distributed random numbers
x = random.randn(5,5)
x

array([[ 1.5195996 , -0.82985387,  1.23473343,  2.07741039, -0.2844459 ],
       [-0.78032552, -1.41556775, -1.0566041 ,  1.24290503,  0.71577729],
       [ 0.09017014,  1.23592648,  0.68061909,  0.41638668, -0.08805148],
       [-0.52262056,  1.23446267,  0.2966873 , -0.69520881,  2.20466865],
       [ 0.07146863, -0.13462973, -0.14293549, -0.32379595,  2.60412183]])

In [125]:
x.dtype

dtype('float64')

In [134]:
x = np.ones(2, dtype=int)
x

array([1, 1])

##### random.randint


- random.randint(x) --> random int (tapi bukan untuk data array, hanya mengambil data acak)
- random.randint(x, y, size=a) -->  random data integer antara x dan y dengan ukuran array 1D a (ukuran maksudnya banyak datanya a)
- random.randint(x, y, size=(a, b, c)) -->  random data integer antara x dan y dengan ukuran array 3D row a, column b, depth c 

In [133]:
random.randint(10)

2

In [137]:
random.randint(2, 10, size=4)

array([9, 6, 2, 4])

In [138]:
random.randint(2, 10, size=(4,2,2))

array([[[9, 5],
        [7, 2]],

       [[2, 2],
        [6, 5]],

       [[9, 4],
        [5, 3]],

       [[4, 3],
        [8, 4]]])

---

## Exercise 2

1. Generate a 1-D array containing 5 random integers from 0 to 100:

In [1]:
from numpy import random
a = random.randint(0, 101, size=5)
a

array([52, 95, 90,  7, 74])

In [2]:
a.size

5

2. Generate a 2-D array with 3 rows, each row contains 5 random integers from 0 to 100

In [3]:
b= random.randint(0, 101, size=(3,5))
b

array([[32, 26, 35, 93, 35],
       [94, 44, 35, 89, 43],
       [ 0, 84, 55, 60, 10]])

In [148]:
b.shape

(3, 5)

3. Generate a 1-D array of 30 evenly spaced elements between 1.5 and 5.5, inclusive.

In [151]:
np.linspace(1.5, 5.5, 30)

array([1.5       , 1.63793103, 1.77586207, 1.9137931 , 2.05172414,
       2.18965517, 2.32758621, 2.46551724, 2.60344828, 2.74137931,
       2.87931034, 3.01724138, 3.15517241, 3.29310345, 3.43103448,
       3.56896552, 3.70689655, 3.84482759, 3.98275862, 4.12068966,
       4.25862069, 4.39655172, 4.53448276, 4.67241379, 4.81034483,
       4.94827586, 5.0862069 , 5.22413793, 5.36206897, 5.5       ])